001 job roles front end
Adnanhoq/TheExtraSemicolon_FrontEnd pull request #16
Opened 2024-08-28 12:32 UTC by Adnanhoq

2024-08-28 14:44 UTC, Leebee1392 commented on views/jobRoles.njk
> +    <meta charset="UTF-8">
Remove unnecessary screenshot from ticket

2024-08-28 14:47 UTC, Adnanhoq commented on src/app.ts
> +app.get('/test', getAllDatabases);
Im trying to merge first 😂

2024-08-28 14:47 UTC, Adnanhoq commented on src/models/JobRoleResponse.ts
> +    locations: String,
No, as the SQL query returns it as a string

2024-08-28 14:47 UTC, Adnanhoq commented on src/models/JobRoleResponse.ts
> +    capability: String,
No, as the SQL query returns it as a string

2024-08-28 14:47 UTC, Adnanhoq commented on src/models/JobRoleResponse.ts
> +    band: String,
No, as the SQL query returns it as a string

2024-08-28 14:48 UTC, Adnanhoq commented on src/services/JobRoleService.ts
> +axios.defaults.baseURL = process.env.API_URL || 'http://localhost:8080/';
Done

2024-08-28 14:49 UTC, Adnanhoq commented on views/jobRoles.njk
> +                    <a href = "./jobRoleDetail" target="_blank" class="jobCard">
Fixed

2024-08-28 14:49 UTC, Adnanhoq commented on views/jobRoles.njk
> +                            <div class="card-body">
css doesn't like me, i'll try again

2024-08-28 14:50 UTC, Adnanhoq commented on views/jobRoles.njk
> +                                <p class="card-text"><strong>Closing Date:</strong> {{ role.closingDate | date }}</p>
I have done this in filters folder

2024-08-28 14:50 UTC, Adnanhoq commented on views/jobRoles.njk
> +    <meta charset="UTF-8">
Done

2024-08-29 08:48 UTC, Adnanhoq commented on src/app.ts
> +app.get('/test', getAllDatabases);
I can't change this as I don't have his files or dependencies

2024-08-29 09:50 UTC, Leebee1392 requested changes
Are you sure this meets requirements of the ticket?

2024-08-29 09:50 UTC, Leebee1392 commented on src/models/JobRoleResponse.ts
> +    locations: String,
Your database design has enums so it should match your code no matter what the database returns

2024-08-29 09:50 UTC, Leebee1392 commented on src/models/JobRoleResponse.ts
> +    capability: String,
Your database design has enums so it should match your code no matter what the database returns

2024-08-29 09:50 UTC, Leebee1392 commented on src/models/JobRoleResponse.ts
> +    band: String,
Your database design has enums so it should match your code no matter what the database returns

2024-08-29 09:50 UTC, Leebee1392 commented on test/unit/controllers/JobRoleControllerTests.ts
This is still empty?

2024-08-29 09:50 UTC, Leebee1392 commented on views/jobRoles.njk
> +                            <div class="card-body">
I can't see a new screenshot so I can't verify

2024-08-29 09:50 UTC, Leebee1392 commented on views/jobRoles.njk
> +                                <p class="card-text"><strong>Closing Date:</strong> {{ role.closingDate | date }}</p>
I can't see a new screenshot so I can't verify

2024-08-29 09:50 UTC, Leebee1392 commented on src/services/JobRoleService.ts
> +export const URL: string = "/api/job-roles/";
I don't think this is correct

2024-08-30 09:18 UTC, Leebee1392 requested changes
Your configuration is breaking the accessibility tests and will probably break other tests in the future.

![image](https://github.com/user-attachments/assets/d67e01a1-a455-41f4-9fe1-8b189a238554)

2024-08-30 09:18 UTC, Leebee1392 commented on src/controllers/JobRoleController.ts
> +    console.log(jobRole)
Needs to be taken out

2024-08-30 09:18 UTC, Leebee1392 commented on src/models/JobRoleResponse.ts
> +    locations: string;
Make these enums

2024-08-30 09:18 UTC, Leebee1392 commented on src/models/JobRoleResponse.ts
> +    capability: string;
Make these enums

2024-08-30 09:18 UTC, Leebee1392 commented on src/models/JobRoleResponse.ts
> +    band: string;
Make these enums

2024-08-30 09:18 UTC, Leebee1392 commented on src/models/JobRoleResponse.ts
> +    locations: string;
Should this be an array?

2024-08-30 09:18 UTC, Leebee1392 commented on src/services/JobRoleService.ts
> +        const response: AxiosResponse<JobRoleResponse[]> = await axios.get("http://localhost:8080/api/job-roles");
No hardcoded URLs

2024-08-30 09:18 UTC, Leebee1392 commented on tsconfig.json
> +        "./.env",
Should not have either of these in the include section

2024-08-30 09:18 UTC, Leebee1392 commented on views/jobRoles.njk
> +                                <p class="card-text"><strong>Closing Date:</strong> {{ role.closingDate | date }}</p>
The date still isn't correct

2024-08-30 09:18 UTC, Leebee1392 commented on src/services/TestService.ts
>          console.log(config.API_URL);
Remove log

2024-08-30 09:18 UTC, Leebee1392 commented on src/services/TestService.ts
> +
Remove unnecessary line

2024-08-30 14:05 UTC, Leebee1392 approved these changes

2024-09-02 13:14 UTC, Leebee1392 approved these changes

2024-09-02 13:15 UTC, Leebee1392 requested changes
Merge conflicts

2024-09-03 10:18 UTC, Leebee1392 approved these changes

2024-09-03 10:19 UTC, AZZohaib approved these changes

2024-09-03 12:39 UTC, merged